### ISSUE TITLE
Extension Identifier

### ISSUE THREAD

**Issue by ChristianToepfer** [JulienCroain/private-extension-manager#1]
Packages from the same publisher, can not be identified. 168d562dac4637ae43027725ae3b9085b932d317 
I think `extension.name` not used in `getExtensionIdentifer`

A Folder with  
> juliencroain.markdown-viewer-1.0.0.vsix
> juliencroain.private-extension-manager-1.4.3.vsix

PRIVATE EXTENSIONS shows: **markdown-viewer juliecroain(1.4.3)  Update**

**Comment by JulienCroain** [comment]
Hi @ChristianToepfer 

I made a mistake in the `getExtensionIdentifer`, I used `name` instead of `id` on `extension`.
The fix is ready and a new version will be available soon.

Thank you

**Comment by JulienCroain** [comment]
Extension v1.4.4 released on [MarketPlace](https://marketplace.visualstudio.com/items?itemName=juliencroain.private-extension-manager) with the fix.

**Comment by ChristianToepfer** [comment]
works fine. Thanks!
Christian
