### ISSUE TITLE
Little Bug

### ISSUE THREAD

**Issue by BorakLeRouge** [JulienCroain/private-extension-manager#10]
Hello
Sorry for my bad English.
We have a problem with the "Install a New version" context menu of your extension, which can be found in many other extensions.
Otherwise, your extension is really great.
Thank you

[https://drive.google.com/file/d/1g5zGzSamSwrLN3m4VOPipzqbMljFvqp2/view?usp=sharing](url)

**Comment by JulienCroain** [comment]
Hello,

Thanks for your comment.
I forgot a condition for this context menu.
This is resolved now.

I deploy a new version quickly.

Julien

**Comment by JulienCroain** [comment]
Hi,

The version 1.4.8 fix this issue.

Julien
