### ISSUE TITLE
[Adoption Required] Use `vscode.extensions.getExtension('vscode.references-view')`

### ISSUE THREAD

**Issue by jrieken** [JulienCroain/private-extension-manager#26]
VS Code Team here 👋 

In June we have renamed the references viewlet extension. Its NEW name identifier is `vscode.references-view` (old was `ms-vscode.references-view`, different publisher). This extension still uses the old form when calling the `getExtension` API. With the September milestone and release this will NOT work anymore and the new identifier must be used, until then both variants will work. See https://github.com/microsoft/vscode/issues/153320 and https://github.com/microsoft/vscode/issues/152834 for context and details

Let us know if you have follow-up question. 

Happy Coding

**Comment by JulienCroain** [comment]
Thanks for the issue.
But, in this extension we manage only extensions in development on local file system.
We don't have any explicit mention of `vscode.references-view`.
I think we are not impact with this rename.
