### ISSUE TITLE
Newest version of readme is not shown with multiple VSIX versions in directory

### ISSUE THREAD

**Issue by rlivings39** [JulienCroain/private-extension-manager#5]
Love the extension! I have multiple versions of the same extension deployed in one of the directories that private-extension-manager looks at. What I notice is that the readme from the oldest version is shown when clicking on it in the tree view. I'd expect the newest version or the version corresponding to the one in the tree view to be shown.

Hacking around a bit, the following seems to get things sorted:
```
diff --git a/src/extensionStore.js b/src/extensionStore.js
index e25e746..75fe5ae 100644
--- a/src/extensionStore.js
+++ b/src/extensionStore.js
@@ -38,16 +38,18 @@ function distinctExtensionsWithAllVersions(extensions) {
     extensions.forEach(extension => {
         if (distinctExtensions[getExtensionIdentifier(extension)])
             return
-        
+
         extension.versions = extensions
             .filter(ex => getExtensionIdentifier(ex) === getExtensionIdentifier(extension))
             .sort((a, b) => compareVersions(a.version, b.version) * -1)
             .map(ext => ({
                 version: ext.version,
-                path: ext.path
+                path: ext.path,
+                readme: ext.readme
             }))
         extension.version = extension.versions[0].version
         extension.path = extension.versions[0].path
+        extension.readme = extension.versions[0].readme
 
         distinctExtensions[getExtensionIdentifier(extension)] = extension
     })
```
but I'm not too confident with how the extension is working.

What do you think?

**Comment by JulienCroain** [comment]
Hi Ryan,

Thanks for your feedback.
I will take a look and come back with a fix as quickly as possible.

Julien,

**Comment by JulienCroain** [comment]
Hi Ryan,

It was the correct fix :)
The version 1.4.6 were published and contains the fix.

Julien,
